### ISSUE TITLE
Cluster Mines on Miranda

### ISSUE THREAD

**Issue by ATLeader** [baranidlo/bench#43]
When I equip Cluster Mines on Miranda they are greyed out immediately during setup as if they have been used. 
<img width="1280" alt="miranda clustermine bug" src="https://user-images.githubusercontent.com/34894255/35787614-18d52a86-09f5-11e8-8cec-3d01f3b69807.png">

**Comment by Sleet01** [comment]
Looks like this is working correctly on the devel branch, so it may have been fixed recently.
You shouldn't be able to equip Bomblet Generator *and* Cluster Mines since B.G. takes up both bomb slots; I think what you're seeing is the B.G. install code not fully uninstalling the Cluster Mines but only partially disabling them.

If you could, please try the following:

1) Delete any saved lists which contain B.G. + Cluster Mines on any ship.

2) Manually recreate one of those lists (such as above) in the current bench site.

3) Report on whether it allows you to put both Bomblet Generator and Cluster mines on the same ship.

If #3 is still working incorrectly then it should get corrected with the next update.

**Comment by baranidlo** [comment]
Miranda has Sabibe which adds third bomb slot, so she can equip Bomblet
with Clusters legally.
I think we should review if the recent changes to ordnance counter (from
boolean to int) has not broken anything..

**Comment by Sleet01** [comment]
Ah, I see the issue.  Okay, it looks like there's a logic error in the "do we have enough slots for all the upgrades of this type" check.  Let me see what I can do.

Edit: Also, the three arrays "upg", "upgrades", and "upgradetype" are not guaranteed to have the same order which screws up a lot of simple approaches to allocating spaces.

**Comment by Sleet01** [comment]
This is now working correctly for both loaded and created squads, at least in the devel branch.  Tested with all three current double-slot upgrade cards and both Sabine and Cad Bane.

**Comment by ATLeader** [comment]
I apologize for the long time delay, but I have still not been able to get it working. I still see the cluster mines greyed out at the beginning of the match.

**Comment by Sleet01** [comment]
Yeah, it's still broken in the release code.  This will work as soon as the release code is updated from the devel branch.

**Comment by ATLeader** [comment]
Ok! Thank you! I can appreciate the time and effort taking over a project like this can take! Excellent work!

**Comment by Sleet01** [comment]
This should be working correctly now.  Please file a new bug of any other Sabine-related issues surface.
